[package]
name = "email-watcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "email-watcher"
path = "src/main.rs"

[dependencies]
sddia-daemon-runtime = { path = "../../sddia-daemon-runtime" }
serde_json = "1.0"
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
imap = "2.4"
native-tls = "0.2"
ctrlc = "3.4"
